### ISSUE TITLE
官网例子不生效

### ISSUE THREAD

**Issue by JayTam** [node-casbin/egg-authz#4]

**Comment by JayTam** [comment]
我clone了例子,运行起来,请求头没有Authorization,
所有请求都正常访问,返回{state: true},
不是预期的403

**Comment by hsluoyz** [comment]
@JayTam please use English in this issue (title and text)

**Comment by nodece** [comment]
clone this repo, run [test](https://github.com/node-casbin/egg-authz/blob/master/test/controller/home.test.js) is pass.

**Comment by JayTam** [comment]
I run test successful, and try to run egg-bin,
all api will receive { state: ture },`egg-authz`  doesn't seem to work.

**Comment by nodece** [comment]
Can you provide a demo to reproduce this issue?

**Comment by Alexlz2538** [comment]
it seems koa-authz line 32 is not return false?

**Comment by nodece** [comment]
Yes. client does not have permission for this,  it returns 403 to the client.
