### ISSUE TITLE
how to use it with mongoose adapter？？？

### ISSUE THREAD

**Issue by daolou** [node-casbin/egg-authz#5]

**Comment by hsluoyz** [comment]
Hi, first you can see how we declare the enforcer here: https://github.com/node-casbin/egg-authz#2-create-a-file-in-middleware-directory-to-import-the-module

```js
const enforcer = await Enforcer.newEnforcer('authz_model.conf', 'authz_policy.csv')
```

And in the Mongoose adapter's README here: https://github.com/elasticio/casbin-mongoose-adapter, you see these two lines to define an adapter and use it in an enforcer:

```js
const adapter = await MongooseAdapter.newAdapter('mongodb://your_mongodb_uri:27017');
const enforcer = await newEnforcer(model, adapter);
```

You can see the 2nd parameter of ``newEnforcer()`` is different. You can change this repo's README's 2nd parameter with the adapter.

**Comment by daolou** [comment]
That is to say, I need to use myself adapter but not casbin-mongoose-adapter?

**Comment by hsluoyz** [comment]
You need to use: https://github.com/elasticio/casbin-mongoose-adapter  That's the official Mongoose adapter for Casbin.

**Comment by daolou** [comment]
> You need to use: https://github.com/elasticio/casbin-mongoose-adapter That's the official Mongoose adapter for Casbin.

yeah,I already read it, and I want use it in egg, and there is no example.
In addition, how to do the requesting library only when the first request or write operation, otherwise read the cache

**Comment by hsluoyz** [comment]
```js
// config/config.default.js
const { Enforcer } = require('casbin')
module.exports = {
  middleware: [ 'authz' ],
  authz: {
    enable: true,
    newEnforcer: async() => {
      // load the casbin model and policy from files, database is also supported.
      const adapter = await MongooseAdapter.newAdapter('mongodb://your_mongodb_uri:27017');
      const enforcer = await Enforcer.newEnforcer('authz_model.conf', adapter);
      return enforcer;
    }
  }
}
```
