### ISSUE TITLE
Invalid enforcer

### ISSUE THREAD

**Issue by klren0312** [node-casbin/egg-authz#7]
```
2019-06-02 09:05:24,948 ERROR 5104 [-/::1/-/1368ms GET /] nodejs.Error: Invalid enforcer
    at D:\1file\tlgtc\tlgc-api-server\node_modules\koa-authz\authz.js:25:15

pid: 5104
hostname: DESKTOP-QKBMCV7
```
I see the `koa-authz\authz.js`
![image](https://user-images.githubusercontent.com/10903843/58755401-ff90d500-8515-11e9-8a97-422dd4e7984c.png)

then I console it in egg, it is true
![image](https://user-images.githubusercontent.com/10903843/58755406-1a634980-8516-11e9-9e00-c9ee65fad68f.png)

**Comment by nodece** [comment]
@klren0312 Thanks for you report! I published v2.0.0 to [npm](https://www.npmjs.com/package/egg-authz).
